# Generated by Django 4.0.3 on 2022-05-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstdb', '0002_remove_config_src_config_key_config_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(default='conf', max_length=128, unique=True),
        ),
    ]
